import torch
import torch.nn as nn
from torch.utils.data import DataLoader


def train_one_epoch(model, dataloader, optimizer, criterion, device, epoch):
    model.train()
    total_loss = 0.0
    for batch_idx, (inputs, targets) in enumerate(dataloader):
        inputs  = inputs.to(device)
        targets = targets.to(device)

        optimizer.zero_grad()
        outputs = model(inputs)
        loss    = criterion(outputs, targets)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        if batch_idx % 10 == 0:
            print(f"Epoch [{epoch}], Batch [{batch_idx}/{len(dataloader)}], Loss: {loss.item():.4f}")

    return total_loss / len(dataloader)


def train_model(model, train_loader, val_loader, config):
    device = config.get('device', 'cpu')
    model  = model.to(device)

    optimizer = torch.optim.Adam(model.parameters(), lr=config['learning_rate'])
    criterion = nn.MSELoss()  # regression task — was CrossEntropyLoss (classification only)

    best_val_loss = float('inf')

    for epoch in range(config['num_epochs']):
        train_loss = train_one_epoch(model, train_loader, optimizer, criterion, device, epoch)
        val_loss   = validate(model, val_loader, criterion, device)

        print(f"Epoch {epoch+1}/{config['num_epochs']} | Train: {train_loss:.4f} | Val: {val_loss:.4f}")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            if 'checkpoint_path' in config:
                save_checkpoint(model, optimizer, epoch, config['checkpoint_path'])


def validate(model, dataloader, criterion, device):
    model.eval()  # disables dropout, uses batchnorm running stats
    total_loss = 0.0
    with torch.no_grad():
        for inputs, targets in dataloader:  # was dataloader.val_data — DataLoader is an iterator
            inputs  = inputs.to(device)
            targets = targets.to(device)
            outputs = model(inputs)
            total_loss += criterion(outputs, targets).item()
    model.train()  # reset flag
    return total_loss / len(dataloader)


def save_checkpoint(model, optimizer, epoch, path):
    torch.save({
        'epoch': epoch,
        'model_state_dict': model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
    }, path)


def load_checkpoint(path, model, optimizer):
    checkpoint = torch.load(path, weights_only=True)
    model.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    epoch = checkpoint['epoch']
    return model, optimizer, epoch


class RNNWithHead(nn.Module):
    """Wrapper combining RNN encoder with output projection head."""
    def __init__(self, input_size, hidden_size, output_size, rnn_type='LSTM'):
        super().__init__()
        self.rnn = build_rnn(rnn_type, input_size=input_size, hidden_size=hidden_size)
        self.fc = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        output, _ = self.rnn(x)
        return self.fc(output[:, -1, :])  # Apply FC to final timestep


class ParquetDataset(torch.utils.data.Dataset):
    """Dataset that loads training pairs from Parquet via subsequence sampling."""
    def __init__(self, file_path, sim_dict, seq_len=20, n_samples=1000):
        self.file_path = file_path
        self.sim_dict = sim_dict
        self.seq_len = seq_len
        self.n_samples = n_samples
        self.feature_cols = ['theta1', 'theta2', 'theta1_dot', 'theta2_dot']

    def __len__(self):
        return self.n_samples

    def __getitem__(self, idx):
        import random
        from data.utils import sample_subsequence
        
        # Sample a window of seq_len+1 timesteps (to create X and y pair)
        df = sample_subsequence(self.file_path, self.sim_dict, n_samples=self.seq_len + 1)
        
        # Extract feature columns and convert to tensor
        features = df.select(self.feature_cols).to_numpy().astype('float32')
        
        # X: first seq_len timesteps, y: next (final) timestep
        X = torch.tensor(features[:-1], dtype=torch.float32)
        y = torch.tensor(features[-1], dtype=torch.float32)
        
        return X, y


if __name__ == "__main__":
    import sys, os
    sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
    from models.layers import build_rnn
    from data.utils import load_sims_from_parquet

    SEQ_LEN    = 20
    N_FEATURES = 4
    BATCH_SIZE = 32
    
    # Path to Parquet file generated by src/main.py
    PARQUET_PATH = os.path.join(os.path.dirname(__file__), '..', '..', 'test_pendulum2.parquet')
    
    # Load simulation metadata from parquet
    try:
        sim_dict = load_sims_from_parquet(PARQUET_PATH)
        print(f"✓ Loaded {len(sim_dict)} simulations from {PARQUET_PATH}")
    except FileNotFoundError:
        print(f"✗ Error: Parquet file not found at {PARQUET_PATH}")
        print("  Make sure src/main.py has been run first to generate pendulum_data.parquet")
        sys.exit(1)

    # Create dataset and dataloaders from Parquet
    dataset = ParquetDataset(PARQUET_PATH, sim_dict, seq_len=SEQ_LEN, n_samples=1000)
    split = int(0.8 * len(dataset))
    
    train_dataset = torch.utils.data.Subset(dataset, range(split))
    val_dataset = torch.utils.data.Subset(dataset, range(split, len(dataset)))
    
    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
    val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE)

    # Build model with RNN + output head
    model = RNNWithHead(input_size=N_FEATURES, hidden_size=64, output_size=N_FEATURES, rnn_type='LSTM')

    config = {
        'learning_rate':   1e-3,
        'num_epochs':      20,
        'device':          'cuda' if torch.cuda.is_available() else 'cpu',
        'checkpoint_path': 'best_model.pt',
    }

    print(f"Training on device: {config['device']}")
    train_model(model, train_loader, val_loader, config)
