"""
Train the LSTM RNNModel on your own parquet data.

SETUP — set the path to your data at the top of this file:

    DATA_PATH = r"C:\path\to\your\data.parquet"

Your parquet must have these columns:
    sim_id        — unique ID per simulation (int or string)
    t             — time (float)
    theta1        — angle 1 (radians)
    theta2        — angle 2 (radians)
    theta1_dot    — angular velocity 1 (rad/s)
    theta2_dot    — angular velocity 2 (rad/s)

If your column names are different, update FEATURE_COLS below.

Run from the project root:
    python project/training/train_rnn.py
"""

#DATA_PATH = r"C:\path\to\your\data.parquet"

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # project/

import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
import polars as pl

from models.RNNModel import RNNModel


# ── CONFIG — edit these ────────────────────────────────────────────────────────

DATA_PATH  = str(ROOT / "training_data.parquet")   # generated by src/main.py
CKPT_PATH  = str(ROOT / "models" / "rnn.pth")

# Column names in your parquet (change if yours differ)
SIM_ID_COL   = "sim_id"
TIME_COL     = "t"
FEATURE_COLS = ["theta1", "theta2", "theta1_dot", "theta2_dot"]

# Training hyperparameters
SEQ_LEN    = 20     # number of timesteps fed as input
HIDDEN     = 64     # LSTM hidden size (must match RNNModel default)
BATCH_SIZE = 64
EPOCHS     = 20
LR         = 1e-3
VAL_SPLIT  = 0.1    # fraction of windows held out for validation

# ── Data loading ───────────────────────────────────────────────────────────────

def build_windows(parquet_path: str, seq_len: int) -> tuple[torch.Tensor, torch.Tensor]:
    """
    Slide a window of seq_len over every simulation.
    Input  X[i]: states at timesteps  t .. t+seq_len-1  →  shape (seq_len, 4)
    Target y[i]: state  at timestep   t+seq_len          →  shape (4,)
    """
    if not Path(parquet_path).exists():
        raise FileNotFoundError(f"Data not found: {parquet_path}")

    df = pl.read_parquet(parquet_path).sort([SIM_ID_COL, TIME_COL])
    sim_ids = df[SIM_ID_COL].unique().to_list()

    sequences, targets = [], []
    for sid in sim_ids:
        arr = (
            df.filter(pl.col(SIM_ID_COL) == sid)
            .select(FEATURE_COLS)
            .to_numpy()
            .astype("float32")
        )
        if arr.shape[0] <= seq_len:
            continue
        for i in range(arr.shape[0] - seq_len):
            sequences.append(arr[i : i + seq_len])
            targets.append(arr[i + seq_len])

    if not sequences:
        raise ValueError("No windows built — check seq_len vs. simulation length.")

    print(f"Built {len(sequences)} windows from {len(sim_ids)} simulations.")
    X = torch.tensor(np.array(sequences), dtype=torch.float32)
    y = torch.tensor(np.array(targets),   dtype=torch.float32)
    return X, y


# ── Training ───────────────────────────────────────────────────────────────────

def _get_device() -> str:
    if torch.cuda.is_available():
        return "cuda"
    try:
        import torch_directml
        return str(torch_directml.device())
    except ImportError:
        return "cpu"


def train(X: torch.Tensor, y: torch.Tensor) -> None:
    device = _get_device()

    # Shuffle and split
    perm    = torch.randperm(len(X))
    X, y    = X[perm], y[perm]
    n_val   = max(1, int(VAL_SPLIT * len(X)))
    X_tr, y_tr   = X[n_val:], y[n_val:]
    X_val, y_val = X[:n_val], y[:n_val]

    train_loader = DataLoader(TensorDataset(X_tr, y_tr),   batch_size=BATCH_SIZE, shuffle=True)
    val_loader   = DataLoader(TensorDataset(X_val, y_val), batch_size=BATCH_SIZE)

    model     = RNNModel(input_size=4, hidden_size=HIDDEN, output_size=4).to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=LR)
    criterion = nn.MSELoss()

    print(f"\nLSTM  |  hidden={HIDDEN}  seq_len={SEQ_LEN}  device={device}")
    print(f"Train: {len(X_tr)} windows   Val: {len(X_val)} windows")
    print(f"\n{'Epoch':>6}  {'Train Loss':>12}  {'Val Loss':>10}  {'Best':>5}")
    print("-" * 42)

    best_val  = float("inf")
    Path(CKPT_PATH).parent.mkdir(parents=True, exist_ok=True)

    for epoch in range(1, EPOCHS + 1):
        model.train()
        train_loss = 0.0
        for xb, yb in train_loader:
            xb, yb = xb.to(device), yb.to(device)
            optimizer.zero_grad()
            loss = criterion(model(xb), yb)
            loss.backward()
            optimizer.step()
            train_loss += loss.item()
        train_loss /= len(train_loader)

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for xb, yb in val_loader:
                val_loss += criterion(model(xb.to(device)), yb.to(device)).item()
        val_loss /= len(val_loader)

        is_best = val_loss < best_val
        if is_best:
            best_val = val_loss
            torch.save(model.state_dict(), CKPT_PATH)

        print(f"{epoch:>6}  {train_loss:>12.6f}  {val_loss:>10.6f}  {'*' if is_best else ''}")

    print(f"\nDone. Best val loss: {best_val:.6f}")
    print(f"Checkpoint saved → {CKPT_PATH}")


# ── Entry point ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    X, y = build_windows(DATA_PATH, SEQ_LEN)
    train(X, y)
