"""
Two modes (auto-detected):

  1. COMPARISON mode  (default when comparisons/ files exist)
     Loads comparisons/actual.parquet   — generated by pendulum.py (symplectic)
     Loads comparisons/rnn_predicted.parquet — RNN autoregressive rollout
     Shows a side-by-side 2×2 plot: actual vs RNN predictions.

  2. TRAINING mode  (fallback when comparisons/ files are absent)
     Trains a fresh LSTM on test_pendulum2.parquet, rolls out autoregressively
     on a held-out simulation, and plots actual vs LSTM predictions.
"""
import sys
import os
from pathlib import Path

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))

import torch
import torch.nn as nn
import polars as pl
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from matplotlib.lines import Line2D
from torch.utils.data import DataLoader

from models.layers import build_rnn


# ── Shared constants ───────────────────────────────────────────────────────────
FEATURE_COLS = ['theta1', 'theta2', 'theta1_dot', 'theta2_dot']
FEATURE_LABELS = [r'$\theta_1$ (rad)', r'$\theta_2$ (rad)',
                  r'$\dot{\theta}_1$ (rad/s)', r'$\dot{\theta}_2$ (rad/s)']


# ── Comparison mode ────────────────────────────────────────────────────────────

def plot_comparison(actual_parquet: str, predicted_parquet: str,
                    hnn_parquet: str | None = None, seq_len: int = 20) -> None:
    """
    Side-by-side 2×2 plot comparing:
      - Actual trajectory (pendulum.py symplectic integrator, green)
      - RNN autoregressive predictions (red dashed)
      - HNN RK4 rollout (blue dotted) — optional, shown when hnn_parquet is provided
    """
    actual_df = pl.read_parquet(actual_parquet).sort("t")
    pred_df   = pl.read_parquet(predicted_parquet).sort("t")

    actual = actual_df.select(FEATURE_COLS).to_numpy()
    pred   = pred_df.select(FEATURE_COLS).to_numpy()
    time_a = actual_df["t"].to_numpy()
    time_p = pred_df["t"].to_numpy()

    hnn_data  = None
    time_hnn  = None
    if hnn_parquet and Path(hnn_parquet).exists():
        hnn_df   = pl.read_parquet(hnn_parquet).sort("t")
        hnn_data = hnn_df.select(FEATURE_COLS).to_numpy()
        time_hnn = hnn_df["t"].to_numpy()

    # Wrap theta1 and theta2 to [-π, π] for display
    for col in range(2):
        actual[:, col] = (actual[:, col] + np.pi) % (2 * np.pi) - np.pi
        pred[:, col]   = (pred[:, col]   + np.pi) % (2 * np.pi) - np.pi
        if hnn_data is not None:
            hnn_data[:, col] = (hnn_data[:, col] + np.pi) % (2 * np.pi) - np.pi

    pred_start_t = time_p[0]

    fig, axes = plt.subplots(2, 2, figsize=(14, 8))
    fig.suptitle(
        "Actual (pendulum.py)  vs  RNN  vs  HNN\n"
        f"Initial conditions: θ₁={actual[0, 0]:.3f} rad, θ₂={actual[0, 1]:.3f} rad  |  "
        f"RNN seed = first {seq_len} steps",
        fontsize=12,
    )

    for i, (ax, name, ylabel) in enumerate(zip(axes.flat, FEATURE_COLS, FEATURE_LABELS)):
        ax.plot(time_a, actual[:, i], color="#27ae60", lw=1.8, label="Actual (pendulum.py)")
        ax.plot(time_p, pred[:, i],   color="#e74c3c", lw=1.5, ls="--", label="RNN predicted")
        if hnn_data is not None:
            ax.plot(time_hnn, hnn_data[:, i], color="#2980b9", lw=1.5, ls=":", label="HNN (RK4)")
        ax.axvline(pred_start_t, color="grey", ls=":", lw=1.2, label="RNN start")
        ax.set_title(name, fontsize=11)
        ax.set_xlabel("time (s)")
        ax.set_ylabel(ylabel)
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.25)

    plt.tight_layout()
    plt.show()


# ── Training mode (original behaviour) ────────────────────────────────────────

class _RNNWithHead(nn.Module):
    def __init__(self, input_size, hidden_size, output_size, rnn_type='LSTM'):
        super().__init__()
        self.rnn = build_rnn(rnn_type, input_size=input_size, hidden_size=hidden_size)
        self.fc  = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        output, _ = self.rnn(x)
        return self.fc(output[:, -1, :])


def _run_training_mode(parquet_path: str) -> None:
    SEQ_LEN     = 20
    N_FEATURES  = 4
    HIDDEN_SIZE = 64
    BATCH_SIZE  = 64
    EPOCHS      = 30
    LR          = 1e-3
    DEVICE      = 'cuda' if torch.cuda.is_available() else 'cpu'

    df      = pl.read_parquet(parquet_path)
    sim_ids = df['sim_id'].unique().to_list()

    test_sim_id   = sim_ids[-1]
    train_sim_ids = sim_ids[:-1]

    def build_windows(data_df, sid_list, seq_len):
        Xs, ys = [], []
        for sid in sid_list:
            vals = (
                data_df.filter(pl.col('sim_id') == sid)
                .sort('t')
                .select(FEATURE_COLS)
                .to_numpy()
                .astype('float32')
            )
            for i in range(len(vals) - seq_len):
                Xs.append(vals[i : i + seq_len])
                ys.append(vals[i + seq_len])
        return np.array(Xs), np.array(ys)

    print("Building training windows...")
    X_train, y_train = build_windows(df, train_sim_ids, SEQ_LEN)

    mean = X_train.reshape(-1, N_FEATURES).mean(axis=0)
    std  = X_train.reshape(-1, N_FEATURES).std(axis=0) + 1e-8

    X_train = (X_train - mean) / std
    y_train = (y_train - mean) / std

    dataset      = torch.utils.data.TensorDataset(
        torch.tensor(X_train), torch.tensor(y_train)
    )
    train_loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)

    model     = _RNNWithHead(N_FEATURES, HIDDEN_SIZE, N_FEATURES, rnn_type='LSTM').to(DEVICE)
    optimizer = torch.optim.Adam(model.parameters(), lr=LR)
    criterion = nn.MSELoss()

    print(f"Training on {DEVICE} for {EPOCHS} epochs...")
    for epoch in range(EPOCHS):
        model.train()
        total_loss = 0.0
        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(DEVICE), y_batch.to(DEVICE)
            optimizer.zero_grad()
            loss = criterion(model(X_batch), y_batch)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        print(f"  Epoch {epoch+1:3d}/{EPOCHS} | Loss: {total_loss/len(train_loader):.5f}")

    # Autoregressive rollout on held-out sim
    test_vals = (
        df.filter(pl.col('sim_id') == test_sim_id)
        .sort('t')
        .select(FEATURE_COLS)
        .to_numpy()
        .astype('float32')
    )
    test_t = (
        df.filter(pl.col('sim_id') == test_sim_id)
        .sort('t')['t']
        .to_numpy()
    )

    seed_norm = (test_vals[:SEQ_LEN] - mean) / std
    model.eval()
    window      = seed_norm.copy()
    predictions = []
    with torch.inference_mode():
        for _ in range(len(test_vals) - SEQ_LEN):
            x   = torch.tensor(window[np.newaxis]).to(DEVICE)
            out = model(x).cpu().numpy()[0]
            predictions.append(out)
            window = np.vstack([window[1:], out])

    predictions = np.array(predictions) * std + mean
    actual      = test_vals[SEQ_LEN:]
    time_axis   = test_t[SEQ_LEN:]

    # Wrap theta1 and theta2 to [-π, π] for display
    for col in range(2):
        actual[:, col]      = (actual[:, col]      + np.pi) % (2 * np.pi) - np.pi
        predictions[:, col] = (predictions[:, col] + np.pi) % (2 * np.pi) - np.pi

    # Plot
    fig, axes = plt.subplots(2, 2, figsize=(14, 8))
    fig.suptitle(f'LSTM (trained from scratch) vs Actual — sim: {test_sim_id}', fontsize=13)

    for i, (ax, name, ylabel) in enumerate(zip(axes.flat, FEATURE_COLS, FEATURE_LABELS)):
        ax.plot(time_axis, actual[:, i],      color="#27ae60", lw=1.5, label='Actual')
        ax.plot(time_axis, predictions[:, i], color="#e74c3c", lw=1.5, ls='--',
                label='LSTM predicted')
        ax.axvline(time_axis[0], color='grey', ls=':', lw=1, label='Prediction start')
        ax.set_title(name, fontsize=11)
        ax.set_xlabel('time (s)')
        ax.set_ylabel(ylabel)
        ax.legend(fontsize=8)
        ax.grid(True, alpha=0.25)

    plt.tight_layout()
    plt.show()


# ── Animation ─────────────────────────────────────────────────────────────────

def animate_comparison(actual_parquet: str, predicted_parquet: str,
                       hnn_parquet: str | None = None,
                       l1: float = 1.0, l2: float = 1.0,
                       trail_len: int = 40, interval: int = 50,
                       seq_len: int = 20) -> None:
    """
    Animate actual, RNN, and HNN double pendulums simultaneously.
    Each is shown as two arms + a trailing path for the tip.
    Plays back at roughly real time (interval=50ms ≈ dt=0.05s).
    """
    actual_df = pl.read_parquet(actual_parquet).sort("t")
    pred_df   = pl.read_parquet(predicted_parquet).sort("t")

    times = actual_df["t"].to_numpy()
    N     = len(times)

    def to_xy(df):
        th1 = df["theta1"].to_numpy()
        th2 = df["theta2"].to_numpy()
        x1 =  l1 * np.sin(th1)
        y1 = -l1 * np.cos(th1)
        x2 = x1 + l2 * np.sin(th2)
        y2 = y1 - l2 * np.cos(th2)
        return np.column_stack([x1, y1]), np.column_stack([x2, y2])

    a_m1, a_m2 = to_xy(actual_df)
    r_m1, r_m2 = to_xy(pred_df)

    has_hnn = hnn_parquet and Path(hnn_parquet).exists()
    if has_hnn:
        hnn_df   = pl.read_parquet(hnn_parquet).sort("t")
        h_m1, h_m2 = to_xy(hnn_df)

    # ── Figure setup ──────────────────────────────────────────────────────────
    fig, ax = plt.subplots(figsize=(7, 7))
    lim = l1 + l2 + 0.3
    ax.set_xlim(-lim, lim)
    ax.set_ylim(-lim, lim)
    ax.set_aspect("equal")
    ax.grid(True, alpha=0.2)
    ax.plot(0, 0, "k.", ms=10, zorder=5)   # fixed pivot

    def make_pendulum(color, ls="-"):
        arm1,  = ax.plot([], [], ls,  color=color, lw=2.0)
        arm2,  = ax.plot([], [], ls,  color=color, lw=2.0)
        bob1,  = ax.plot([], [], "o", color=color, ms=9,  zorder=4)
        bob2,  = ax.plot([], [], "o", color=color, ms=11, zorder=4)
        trail, = ax.plot([], [], "-",  color=color, lw=1.0, alpha=0.35)
        return arm1, arm2, bob1, bob2, trail

    a_arm1, a_arm2, a_bob1, a_bob2, a_trail = make_pendulum("#27ae60", "-")
    r_arm1, r_arm2, r_bob1, r_bob2, r_trail = make_pendulum("#e74c3c", "--")
    if has_hnn:
        h_arm1, h_arm2, h_bob1, h_bob2, h_trail = make_pendulum("#2980b9", ":")

    legend = [
        Line2D([0], [0], color="#27ae60", lw=2,       label="Actual"),
        Line2D([0], [0], color="#e74c3c", lw=2, ls="--", label="RNN"),
    ]
    if has_hnn:
        legend.append(Line2D([0], [0], color="#2980b9", lw=2, ls=":", label="HNN"))
    ax.legend(handles=legend, loc="upper right", fontsize=9)

    title = ax.set_title("t = 0.00 s")

    # ── Per-frame update ──────────────────────────────────────────────────────
    def _set_pendulum(arm1, arm2, bob1, bob2, trail, m1, m2, frame, trail_arr):
        arm1.set_data([0, m1[0]], [0, m1[1]])
        arm2.set_data([m1[0], m2[0]], [m1[1], m2[1]])
        bob1.set_data([m1[0]], [m1[1]])
        bob2.set_data([m2[0]], [m2[1]])
        t0 = max(0, frame - trail_len)
        trail.set_data(trail_arr[t0:frame + 1, 0], trail_arr[t0:frame + 1, 1])

    def update(frame):
        # Actual
        _set_pendulum(a_arm1, a_arm2, a_bob1, a_bob2, a_trail,
                      a_m1[frame], a_m2[frame], frame, a_m2)

        # RNN — seed period mirrors actual; prediction period uses rnn data
        if frame < seq_len:
            rm1_f, rm2_f = a_m1[frame], a_m2[frame]
            r_trail.set_data([], [])
        else:
            ri = min(frame - seq_len, len(r_m1) - 1)
            rm1_f, rm2_f = r_m1[ri], r_m2[ri]
            t0 = max(0, ri - trail_len)
            r_trail.set_data(r_m2[t0:ri + 1, 0], r_m2[t0:ri + 1, 1])
        r_arm1.set_data([0, rm1_f[0]], [0, rm1_f[1]])
        r_arm2.set_data([rm1_f[0], rm2_f[0]], [rm1_f[1], rm2_f[1]])
        r_bob1.set_data([rm1_f[0]], [rm1_f[1]])
        r_bob2.set_data([rm2_f[0]], [rm2_f[1]])

        # HNN
        if has_hnn:
            hi = min(frame, len(h_m1) - 1)
            _set_pendulum(h_arm1, h_arm2, h_bob1, h_bob2, h_trail,
                          h_m1[hi], h_m2[hi], hi, h_m2)

        title.set_text(f"t = {times[frame]:.2f} s")
        return []

    FuncAnimation(fig, update, frames=N, interval=interval, blit=False)
    plt.tight_layout()
    plt.show()


# ── Entry point ────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    root            = Path(__file__).resolve().parents[2]
    actual_path     = root / "comparisons" / "actual.parquet"
    pred_path       = root / "comparisons" / "rnn_predicted.parquet"

    hnn_path = root / "comparisons" / "hnn_predicted.parquet"

    if actual_path.exists() and pred_path.exists():
        print("Comparison files found — running comparison mode.")
        print(f"  actual:    {actual_path}")
        print(f"  predicted: {pred_path}")
        if hnn_path.exists():
            print(f"  hnn:       {hnn_path}")
        hnn_arg = str(hnn_path) if hnn_path.exists() else None
        plot_comparison(str(actual_path), str(pred_path), hnn_parquet=hnn_arg)
        animate_comparison(str(actual_path), str(pred_path), hnn_parquet=hnn_arg)
    else:
        print("No comparison files found — running training mode.")
        parquet_path = str(root / "test_pendulum2.parquet")
        if not Path(parquet_path).exists():
            print(f"Error: training parquet not found at {parquet_path}")
            print("Run src/main.py first to generate it, or run RNNModel.py to generate comparison data.")
            sys.exit(1)
        _run_training_mode(parquet_path)
